config/routes.rb
Rails.application.routes.draw do
	resources :pages
  get "home", to: "pages#home"
  resources :projects
  root "projects#index"
  get "shoppingcart", to: "projects#shoppingcart"
  get "signin", to: "projects#signin"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks
	validates_presence_of :name, :description
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@pro = Project.all.limit(100)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end
  def shoppingcart
    
  end
  def signin
    
  end
  def account
    
  end
  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer navbar-fixed-bottom">
	<div class="container-fluid">
		<nav>
			<ul>
				<li><%=link_to "About Us", "#"%></li>
				<li><%=link_to "Terms of uses", "#"%></li>
				<li><%=link_to "@copyright", "#"%></li>
				<li><%=link_to "Help", "#"%></li>
				<li><%=link_to "Contact Us", "#"%></li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
     
      <div class="navbar-header">

     <span><span><%= image_tag("logos/logo.png", width: '60px')%></span> <%= link_to "Post", root_path, id: "logo" %></span>
        <span class="beta">Beta</span>
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li> <%= link_to "Projects", home_path%></li>
          <li><%= link_to "Shopping Cart", shoppingcart_path %></li>
         
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="drop"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="dropdown-item" id="drop"><%= link_to "Profile", "#" %></li>
                <li class="divider"></li>
                <li class="dropdown-item" id="drop"><%= link_to "Sign out", "#", method: "delete" %></li>
              </ul>
            </li>
         
            <li><%= link_to "Sign in", signin_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%=render 'layouts/header'%>
     <%= render 'layouts/footer'%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Projects</h1>
<% @pro.each do |project|%>
	<p><strong>Project Name  </strong><%=project.name%></p>
	<p><strong>Project Description  </strong><%=project.description%></p>
<% end %>

app/views/pages/show.html.erb
<h1>hello</h1>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/account.html.erb
<h1>This is your account section</h1>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/shoppingcart.html.erb
<h1>This is your cart</h1>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/signin.html.erb
</hr>
<form class="need-validated" action="#">
	<div class="form-group">
		<label for="email">Email Address:</label>
		<input type="email" class="form-control" id="email" placeholder="Email" required> 
		<div class="valid-feedback">Valid</div>
		<div class="invalid-feedback">Please Filled it</div>
	</div>
	<div class="form-group">
		<label for="pwd">Password</label>
		<input type="text" class="form-control" id="pwd" placeholder="Password" required>
		<div class="valid-feedback">Valid</div>
		<div class="invalid-feedback">Please Filled it</div>
	</div>
	<div class="form-group form-check">
	<label class="form-check-level">
	<input type="checkbox" class="form-check-input">Remember me</label>
</div>
<button type="submit" class="btn btn-primary">Submit
	
</button>
</form>